server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db-documents-hub}
    username: ${DB_USER:documents-user}
    password: ${DB_PASSWORD:documents-pass}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8080/realms/DocumentApp}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    baseline-version: 0

  jpa:
    generate-ddl: false

keycloak:
  admin:
    server-url: ${KEYCLOAK_ADMIN_URL:http://localhost:8080/}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:DocumentAppClient}
    realm: ${KEYCLOAK_ADMIN_REALM:DocumentApp}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:iLTNvQeAk6zfpEvuTzeVFSfGx6m5blFc}
    grant-type: ${KEYCLOAK_ADMIN_GRANT_TYPE:client_credentials}

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1

document:
  directory: ./abouelmakarim_norsys/src/main/java/com/norsys/fr/files/

